<?xml version="1.0"?>
<package format="3">
  <name>hexacopter_sim</name>
  <version>0.0.0</version>
  <description>Hexacopter simulation</description>
  <maintainer email="mohit@todo.todo">mohit</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>joint_state_publisher</depend>
  <depend>robot_state_publisher</depend>
  <exec_depend>xacro</exec_depend>
  <depend>ros_gz</depend>
  <depend>ros_gz_sim</depend>
  <depend>ros_gz_bridge</depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
